services:
  back:
    build: "tp-docker/simple-api-student-main"
    container_name: simpleapistudent-container
    environment:
      - URL=${URL}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - my-network
    depends_on:
      - db

  db:
    build: "tp-docker/db"
    container_name: custom-postgres-container
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - my-network
    volumes:
      - ./tp-docker/data:/var/lib/postgresql/data

  http:
    build: "tp-docker/proxy"
    container_name: proxy-container
    ports:
      - "80:80"
    networks:
      - my-network
    depends_on:
      - back

networks:
    my-network: