services:
  database:
    build: "database"
    environment:
      - POSTGRES_PASSWORD=pwd
    volumes:
      - db-volume:/var/lib/postgresql/data
    networks:
      - my-network

  simple-api:
    build: "simple-api"
    environment:
      - DATABASE_HOST=database
      - DATABASE_PASSWORD=pwd
    ports:
      - "8080:8080"
    networks:
      - my-network

  httpd:
    build: "http-server"
    ports:
      - "80:80"
    networks:
      - my-network

  front:
    build: "devops-front-main"
    environment:
      - VUE_APP_API_URL=http://localhost/api
    ports:
      - "8080:80"
    networks:
      - my-network


networks:
  my-network:

volumes:
  db-volume:
