- hosts: all # on cible toutes les machines
  gather_facts: true # on récupère les infos sur les machines
  become: true # on passe en root
  vars:
    ansible_python_interpreter: /usr/bin/python3 # on spécifie l'interpréteur Python
  roles: # on appelle les roles
    # - docker
    - network 
    # - copy
    - database
    - app
    - proxy
    - front
