- name: Launch Proxy Container
  community.docker.docker_container:
    name: http-server
    image: evlacy/tp-devops-httpd:latest
    pull: yes
    networks:
      - name: appnetwork2
    ports:
      - "80:80"
