- name: Launch Proxy Container
  community.docker.docker_container:
    name: http-server
    image: evlacy/tp-devops-httpd:latest
    pull: yes
    networks:
      - name: appnetwork
      - name: appnetwork3
    ports:
      - "80:80"
      - "8080:8080"
