name: Deploy

on:
  push:
    branches:
      - prod
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Run Ansible Playbook
        env:
          ANSIBLE_PRIVATE_KEY: ${{ secrets.RSA_PRIVATE_KEY }}
        run: |
          echo "${ANSIBLE_PRIVATE_KEY}" > private_key.pem
          chmod 600 private_key.pem
          ansible-playbook -i ansible/inventories/setup.yml ansible/playbook.yml --private-key private_key.pem
          rm -f private_key.pem
