name: CI devops 2025

on:
  push:
    branches: [ main, develop ]
  pull_request:

jobs:
  test-backend: 
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./github 

    steps:
      # Checkout GitHub code
      - uses: actions/checkout@v2.5.0

      # Set up JDK 21 using actions/setup-java@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '21'

      # Build and test with Maven
      - name: Build and test with Maven
        run: mvn -B package --file simple-api/pom.xml
